# Generated by Django 5.0 on 2024-01-19 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text',
            old_name='user',
            new_name='user_id',
        ),
    ]
