# Generated by Django 5.0.6 on 2024-05-17 19:02

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='lessons')),
                ('description', ckeditor.fields.RichTextField()),
                ('show', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='languages.language')),
            ],
            options={
                'verbose_name': 'lesson',
                'verbose_name_plural': 'Lessons',
            },
        ),
    ]
