# Generated by Django 5.0.6 on 2024-05-17 19:18

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_eventtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', ckeditor.fields.RichTextField(verbose_name='question')),
                ('a', ckeditor.fields.RichTextField(verbose_name='a варият')),
                ('b', ckeditor.fields.RichTextField(verbose_name='б варият')),
                ('c', ckeditor.fields.RichTextField(verbose_name='в варият')),
                ('d', ckeditor.fields.RichTextField(verbose_name='г варият')),
                ('answer', models.CharField(choices=[('0', 'A'), ('1', 'B'), ('2', 'C'), ('3', 'D')], max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('eventTest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.eventtest')),
            ],
            options={
                'verbose_name': 'tests',
                'verbose_name_plural': 'tests',
            },
        ),
    ]
