# Generated by Django 5.0.6 on 2024-05-17 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_tests'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tests',
            options={'verbose_name': 'question', 'verbose_name_plural': 'Questions'},
        ),
    ]
